feat(playbutton): change play button text based on userData
jellyfin/jellyfin-vue pull request #112
Opened 2020-09-22 18:25 UTC by Camc314

Changes play button text depending on user watch status

 - Play Episode X
 - Resume Episode X
 - Play Movie
 - Resume Movie

Falls back to play if no user data or if item type is not series/movie

2020-09-22 18:54 UTC, KristupasSavickas commented on pages/item/_itemId/index.vue
> +      console.log(this);
😱

2020-09-22 19:49 UTC, Camc314 commented on pages/item/_itemId/index.vue
> +      console.log(this);
Oops

2020-09-22 19:49 UTC, Camc314 commented on pages/item/_itemId/index.vue
> +      console.log(this);
Bad habits

2020-09-23 03:36 UTC, MrTimscampi requested changes
We should probably start to break this into more sub-components.

I could see one for the play button (potentially combining it with the circle buttons for the cards, to have one component used everywhere) and one for the subtitle line with date, runtime and so on (The equivalent of jf-web's mediaInfo module).

2020-09-23 03:36 UTC, MrTimscampi commented on pages/item/_itemId/index.vue
> +    renderPlayButton(): string {
Should be a computed property like `playButtonText`.

2020-10-03 02:51 UTC, MrTimscampi commented on pages/item/_itemId/index.vue
> +    renderPlayButton(): string {
@Camc314 Any news on this?

2020-10-20 16:58 UTC, MrTimscampi commented
Closing this, since #184 only has "Play" in the buttons

2020-10-20 16:58 UTC, closed without merging