Style/item space
jellyfin/jellyfin-vue pull request #1160
Opened 2021-05-29 20:16 UTC by ThibaultNocchi

Applies the scoped style to PR #1060

2021-05-29 20:18 UTC, ferferga approved these changes

2021-05-29 20:40 UTC, MrTimscampi requested changes
Does not work, the spacing is still there.

2021-05-29 20:48 UTC, MrTimscampi reviewed
It might also be good to mimic the same behavior for `v-slide-group__next--disabled`, for consistency.

2021-05-29 20:48 UTC, MrTimscampi commented on client/pages/item/_itemId/index.vue
> +.v-slide-group__prev--disabled {
```suggestion
/* stylelint-disable-next-line */
.v-item-group::v-deep .v-slide-group__prev--disabled {
```

2021-05-30 12:36 UTC, MrTimscampi approved these changes

2021-05-30 13:04 UTC, merged