Fix: search
jellyfin/jellyfin-vue pull request #1875
Opened 2023-01-30 13:46 UTC by Janbong

2023-01-30 14:28 UTC, ThibaultNocchi commented on frontend/src/pages/search.vue
> +    ).data.Items;
```suggestion
    ).data.Items || [];
```
Should do the trick :)

2023-01-30 14:28 UTC, ThibaultNocchi commented on frontend/src/pages/search.vue
> +      (item: BaseItemDto) => item.Type === 'Book'
You can use the enum for the type checks, such as this:

```suggestion
      (item: BaseItemDto) => item.Type === BaseItemKind.Book
```

2023-01-30 18:36 UTC, ferferga requested changes
* We should remove the ``Top results`` tab, because the Virtual Grid is not ready to show cards of different sizes (or we shouldn't use virtual grid at all here, which may even be a more sensible solution if we want to keep that tab, which I'm not a fan of because it's horrible). We need to redesign that page functionally anyway.

* I'd say we should keep the functionality of keeping tabs that don't have any items disabled.

2023-02-15 14:39 UTC, ferferga approved these changes

2023-02-15 14:39 UTC, ThibaultNocchi commented on frontend/src/pages/search.vue
> +      router.back();
What do you think of putting the router.back in the performSearch? That way 1. logic is centralized 2. you can quickly erase your sentence and start typing again without being redirected back to the debounced logic.

Also you may want to use watchDebounced from vueuse?

2023-02-15 15:08 UTC, ThibaultNocchi approved these changes

2023-02-18 15:26 UTC, ThibaultNocchi commented on frontend/src/components/Layout/AppBar/SearchField.vue
> +        q: value || undefined
```suggestion
        q: value.trim() || undefined
```

Just an easy QOL change

2023-02-18 16:22 UTC, merged