More small cleanups & chore
jellyfin/jellyfin-vue pull request #1912
Opened 2023-03-26 19:57 UTC by aweebs

3 changes in total:
1. Remove TooltipButton in favour of using the components directly with parent activator (review with whitespace changes off)
2. Support `data-` attributes on any vue components. These get mapped through into the component template root element correctly but were giving typing errors previously.
3. Make favicon and icon paths absolute. Previously when using the `history` router type these would not work correctly unless the user started on the home page.

2023-03-27 08:18 UTC, ferferga requested changes

2023-03-27 08:18 UTC, ferferga commented on frontend/package.json
> -    "comlink": "4.3.1",
Why? Build is failing because of this

2023-03-28 07:42 UTC, aweebs commented
Removed the last commit which removed comlink - my mistake!

2023-03-28 08:02 UTC, ferferga commented
I was thinking that the absolute path doesn't fix the problem properly (so maybe I should revert the change for the ``config.json`` as well).

The absolute paths doesn't handle cases where I want the client to be served in a subpath: ``domain.xyz/vue``

2023-03-28 09:52 UTC, ferferga requested changes
Not all menus and tooltips have been changed to the new syntax.
There are also new lint errors introduced in this PR.

2023-03-29 14:09 UTC, ferferga requested changes
Besides my two comments, I just noticed we could set the activators by default : https://vuetifyjs.com/en/features/global-configuration/#contextual-defaults
Can you ammend your commits to take that into account?

Sorry mate for not thinking about this earlier 😅

2023-03-30 08:01 UTC, ferferga approved these changes

2023-03-30 08:02 UTC, merged