feat: refresh user on page load
jellyfin/jellyfin-vue pull request #1936
Opened 2023-04-07 14:33 UTC by ThibaultNocchi

2023-04-07 15:17 UTC, ferferga requested changes
Why not do this in the plugin initialization? In the auth plugin constructor, for instance.

2023-04-10 17:31 UTC, ThibaultNocchi commented
@ferferga It's implemented now in the constructor :)

2023-04-10 17:38 UTC, ferferga requested changes
This made me realize that we could probably simplify our checks in a lot of places, but that's for another time lol

2023-04-10 17:38 UTC, ferferga commented on frontend/src/plugins/remote/auth/index.ts
> +      );
If there's an user logged in, you don't need the `OneTimeApi`, you can use the global api instance. In fact if there's no global api defined, we can assume there's no current user/server. Check [this](https://github.com/jellyfin/jellyfin-vue/blob/master/frontend/src/plugins/remote/sdk/index.ts#L17-L51)

2023-04-10 18:02 UTC, ferferga commented on frontend/src/plugins/remote/auth/index.ts
> +      );
Fair enough, this reminds me that I need to add a way to debug circular dependencies in Vite.

2023-04-10 18:02 UTC, ferferga approved these changes

2023-04-10 18:02 UTC, merged