feat(noto): add noto sans packages
jellyfin/jellyfin-vue pull request #401
Opened 2020-12-16 21:57 UTC by ferferga

2020-12-16 22:37 UTC, MrTimscampi requested changes

2020-12-16 22:37 UTC, MrTimscampi commented on assets/global.scss
> +  font-family: 'Noto Sans', 'Noto Sans HK', 'Noto Sans JP', 'Noto Sans KR', 'Noto Sans SC', sans-serif;
See `variables.scss`, we're already setting it for a bunch of things via `$body-font-family`.

You can likely add `$heading-font-family`, though. Everything else should use these variables (Everything inside v-app already does, so pretty much all of the client uses it by default).

2020-12-17 00:13 UTC, ferferga commented on assets/global.scss
> +@import 'fontsource-noto-sans/index.css';
Not sure if we should move this to variables as well to keep everything in one place.

2020-12-17 07:39 UTC, MrTimscampi approved these changes

2020-12-17 07:39 UTC, merged