fix(blurhash iamge): add missing alt to image
jellyfin/jellyfin-vue pull request #460
Opened 2020-12-28 09:30 UTC by Camc314

Fix sonarrcloud bug:

 - Add missing `alt` to image

2020-12-28 10:03 UTC, ferferga approved these changes

2020-12-28 14:19 UTC, MrTimscampi commented on components/BlurhashImage.vue
> +        :alt="item.Name"
I don't think all of them should have a name.

For example, the background image on the home header is only illustrative in purpose. On the other hand, logos should have an alt for screen readers.

2020-12-31 03:31 UTC, MrTimscampi requested changes
A better, more flexible way to do this would be to add an `alt` prop, which wouldn't be required and would simply pass its value along to the `alt` property of `img`.

Currently, this implementation is too limiting and doesn't help the users who rely on `alt` to know what they're looking at.

2021-01-01 07:42 UTC, Camc314 commented
> A better, more flexible way to do this would be to add an `alt` prop, which wouldn't be required and would simply pass its value along to the `alt` property of `img`.

I have updated it so the alt now a prop

2021-01-01 09:22 UTC, MrTimscampi approved these changes
The description aren't ideal (It should describe the content and/or the purpose of the image), but it'll do for now :+1:

2021-01-01 09:23 UTC, merged