fix(itemmenu): don't force dark theme
jellyfin/jellyfin-vue pull request #592
Opened 2021-01-17 21:36 UTC by masterkoppa

Don't force dark theme on ItemMenu

## Current
![image](https://user-images.githubusercontent.com/108104/104856466-de464d80-58e0-11eb-870c-f6a2464c8d02.png)

## Fixed
![image](https://user-images.githubusercontent.com/108104/104856443-b2c36300-58e0-11eb-9bc4-c2a2a7d53d7d.png)

## Note
This is my first PR against the new jellyfin-vue repository, so please let me know if there's anything I did wrong or anything I could do better in the future. I found the issue while exploring the new interface. It's looking great!

2021-01-17 22:03 UTC, ferferga requested changes
This doesn't fix the problem.

Afaik, the ``dark`` prop is to indicate that we want that to be in the *inverted* color theme we're using. i.e: be black on light theme and white in dark theme

So, if you remove this, it might look nice in ligh theme, but not in dark. Also, I remember I added that prop because there were specific issues with card overlays, where it looked way too dark in ligh theme. Did you check that?

Try the following:
* Add the prop to the ``v-icon`` instead.
* Change ``HomeHeaderWelcome`` so the item menu component has the ``dark`` prop as false.

2021-01-17 22:23 UTC, MrTimscampi commented
> Afaik, the `dark` prop is to indicate that we want that to be in the _inverted_ color theme we're using. i.e: be black on light theme and white in dark theme

No, it overrides the link to the theme of the `v-app`. So the icon will be white in dark mode and black in light mode.

Since we want to be able to pass the dark prop in some places (Card overlays, for example), the proper fix here would be to set the dark prop to false here: https://github.com/jellyfin/jellyfin-vue/blob/master/components/Layout/HomeHeader/HomeHeaderItems.vue#L124

Or better yet, default it to false and specify true where needed (Which is the proper way props should work)

2021-01-18 00:55 UTC, masterkoppa commented
@ferferga:
I'm not super familiar with the dark/light theme setup here, but from my observation by being `dark = true` by default (and having no overrides) the button was stuck in the dark theme regardless of the setting. With the fix, things looked correct in both light and dark theme.

> default it to false and specify true where needed (Which is the proper way props should work)

That's fair, happy to make that change. Not sure where it should be set to `true`, but I'll take a look around on where it's used.

2021-01-18 01:20 UTC, masterkoppa commented
@MrTimscampi:

Correct me if I'm wrong, but this looks like it's a one off Component for the edit metadata dropdown on a specific item page. (The link you posted is for the home header one, which is different). With this being a one off, do you still think it should have a `dark` prop for overrides?

(Sorry if this sounds wrong / dumb, my background is in React not Vue)

2021-01-18 06:08 UTC, ThibaultNocchi commented
There are for now 4 instances of this component, and it is intended to be used almost everywhere we need the item menu. Do note that the HTML tags are `<item-menu>`

> That's fair, happy to make that change. Not sure where it should be set to true, but I'll take a look around on where it's used.

If you invert the default `dark` data, you'll need to also invert the `dark` prop on all four `<item-menu>`. So everywhere there was `:dark="false"` you drop it, and everywhere there's nothing you add `:dark="true"`.

2021-01-18 07:40 UTC, MrTimscampi commented
> The link you posted is for the home header one, which is different

Ah, indeed, sorry, I posted in passing, late at night :laughing: 

As @ThibaultNocchi said, it's not a one-off, it's intended to be used everywhere we have the three-dots menu, like cards, the item pages, the audio controls, etc (It's already used in most of those places)  
So the override makes sense in this context, since we use them in different places.

As for inverting the prop, the idea is to follow what standard HTML is doing: not having a property makes it be "false". Adding it means it's true (So you can do things like `<item-menu :item="item" dark />`). This is more consistent with what people would expect (I should've caught it when reviewing the original PR that added the component).

> Sorry if this sounds wrong / dumb, my background is in React not Vue

No worries, we've all pretty much been learning Vue on the fly as we work on this :) You contribution is appreciated.

2021-02-09 17:26 UTC, ThibaultNocchi approved these changes

2021-02-09 17:31 UTC, ferferga approved these changes

2021-02-09 17:31 UTC, merged