feat: disable buttons on load or no items and show progress circular in chip while loading
jellyfin/jellyfin-vue pull request #614
Opened 2021-01-21 12:53 UTC by ferferga

That way we avoid popping or bad inputs while content is not loaded

2021-01-22 15:51 UTC, ThibaultNocchi commented
IMO what I'd do is set the disabled props to not required and false by default. What do you think?

2021-01-22 16:37 UTC, ThibaultNocchi requested changes

2021-01-22 16:37 UTC, ThibaultNocchi commented on pages/library/_viewId.vue
> +      </v-chip>
```suggestion
      <v-chip :small="!loading" class="ma-2 hidden-sm-and-down">
        <template v-if="!loading">{{ itemsCount }}</template>
        <v-progress-circular v-else width="2" indeterminate size="15" />
      </v-chip>
```

2021-01-22 20:14 UTC, ferferga commented
@ThibaultNocchi Good point, didn't think about that ^^

I don't mind. However, we're not using those components anywhere else, so this might be a bit moot. And, if at some point we do, having them required by default makes it easy to "force" us to remember that we need to set that prop for better UX, as console messages will pop everywhere reminding that.

But, as said, don't mind it. Thoughts @MrTimscampi @Camc314 ?

2021-01-23 01:02 UTC, MrTimscampi commented
> IMO what I'd do is set the disabled props to not required and false by default. What do you think?

Agreed, it's simply passing something to the component below it, so it should use the same thing, which is false by default and not required.

2021-01-23 01:22 UTC, ferferga commented on pages/library/_viewId.vue
> +        <v-progress-circular v-else width="2" indeterminate size="15" />
Good point 👍.

2021-01-24 15:05 UTC, ThibaultNocchi approved these changes

2021-01-24 15:07 UTC, MrTimscampi approved these changes

2021-01-24 15:07 UTC, merged