Implemented stream selection on item detail page and VideoPlayer
jellyfin/jellyfin-vue pull request #640
Opened 2021-01-31 17:19 UTC by Sergeeeek

Changes:
- Add mediaStreamPreferences Vuex store to store stream selection for each item in a session
- Populate url parameters for `VideoStreamIndex`, `AudioStreamIndex` and `SubtitleStreamIndex` when building video source url

2021-02-03 16:38 UTC, MrTimscampi requested changes
Thanks for the contribution :)

I'm unfortunately not too fond of the implementation of this. I don't think using another store is necessary for this.

What should be done is extending the `play` action in the playback manager to be able to take optional track indexed, which would then be set directly when starting playback.

If they're not passed to the play action, the playback manager automatically sets the default ones. Then simply use the indexes in the playbackManager store when generating the playback URL.

When switching to the next track, check if the indexes are still valid, if not switch back to the default ones.

I'm curious to know what the rest of the Vue team thinks, though.

@ferferga @Camc314 @ThibaultNocchi @dkanada

2021-02-03 16:38 UTC, MrTimscampi commented on components/Item/TrackSelector.vue
> +      console.log(event);
```suggestion
```

2021-02-03 18:44 UTC, Camc314 commented
> What should be done is extending the `play` action in the playback manager to be able to take optional track indexes, which would then be set directly when starting playback.

This is probably an easier method.

2021-02-03 19:07 UTC, dkanada commented
@MrTimscampi just out of curiosity, does the play method already take time as an argument?

2021-02-03 19:24 UTC, ferferga commented
@dkanada Yes

I agree with what others said here: it seems overkill to me to create a single store just for stream selection. In some cases, decoupling stores are a good solution towards maintainability but I don't think this is the case with playback-related stuff: playback stuff makes sense to be as "single-managed" as possible.

I'm not sure if you used the multiple stores approach because dictionaries, as multidimensional objects, have some issues with Vue's reactivity. Imo, **selecting track indexes for each of the items in the queue is overkill**, normally nobody does that job manually and either expect:

• That the default tracks of the next item are used
• That the language of the currently playing show/movie track is chosen for the next one.

We could live perfectly with just integer variables that refer to the currently playing track indexes instead of a dictionary, so if that adds complexity for you, I would go that way. However, if you still want to keep the dictionary way **(which can also be useful, as we could add track selectors to the queue view where users can change those preferences individually)**, move all the logic into the playbackManager store.

Let us know if you need any help with anything 👍🏻.

2021-02-03 21:49 UTC, Sergeeeek commented
Thanks for your feedback everyone. 

I had created a separate store under an assumption that stream indexes for different media sources mean different things, e.g. audio stream 0 in one movie could be English, while in another movie it could be Spanish or something else. 

From your comments I see that maybe it was incorrect. Does Jellyfin server reorder streams based on user preferences? 

Anyway, I will remove the separate store and pass stream indexes into the play method as you suggested.

2021-02-04 08:13 UTC, ThibaultNocchi commented
No, your first assumption was correct. To my knowledge, JF just parses the tracks in the media in the order they are. But what happens usually though is that in a TV show, usually they have the same tracks between each episodes. That's why keeping the same tracks index usually works. :)

2021-02-04 10:42 UTC, MrTimscampi commented
> That's why keeping the same tracks index usually works

That said, there should still be a check if the track is defined and a fallback to the default one :) If the track ends up being different, there isn't much we can do realistically with the current API, but it's easy enough for the user to fix during playback.

2021-02-11 16:22 UTC, ThibaultNocchi commented
@Sergeeeek Hey, are you planning to improve the PR? If yes then no problem, take your time :)

2021-02-11 16:41 UTC, Sergeeeek commented
Yes, I am. Just been a little busy lately :)

On Thu, Feb 11, 2021, 7:23 PM Thibault <notifications@github.com> wrote:

> @Sergeeeek <https://github.com/Sergeeeek> Hey, are you planning to
> improve the PR? If yes then no problem, take your time :)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/jellyfin/jellyfin-vue/pull/640#issuecomment-777616399>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAZZRFYM3OV25VCBMXV4UMTS6P76TANCNFSM4W3RGEBA>
> .
>

2021-02-11 16:57 UTC, ThibaultNocchi commented
No problem then, do what you want :)

2021-06-08 19:29 UTC, closed without merging