chore: replace nuxt-ts with nuxt
jellyfin/jellyfin-vue pull request #805
Opened 2021-02-27 00:25 UTC by ferferga

Nuxt now is built on TypeScript so nuxt-ts is no longer necessary

This removes the warnings at build time.

2021-02-27 00:50 UTC, MrTimscampi requested changes
We can probably remove the dependency itself, too.

2021-02-27 00:51 UTC, MrTimscampi approved these changes
Nevermind, we don't depend on it directly, it's a sub-dependency.

2021-02-27 00:52 UTC, MrTimscampi requested changes
Third time's the charm, we can actually remove `@nuxt/typescript-runtime`

2021-03-01 13:31 UTC, ThibaultNocchi approved these changes

2021-03-01 13:35 UTC, merged