fix(ui): use blurhash image for related items
jellyfin/jellyfin-vue pull request #932
Opened 2021-03-29 02:51 UTC by dkanada

The placeholder for *missing* items doesn't show up but the blurhash looks much better when items are still loading.

2021-03-29 08:32 UTC, ThibaultNocchi approved these changes

2021-03-29 08:58 UTC, ferferga requested changes

2021-03-29 08:58 UTC, ferferga commented on client/components/Item/RelatedItems.vue
> +              <blurhash-image :item="relatedItem" :type="'Primary'" />
```suggestion
              <blurhash-image :item="relatedItem" />
```
This is not needed because it's the default.

2021-03-30 05:51 UTC, MrTimscampi approved these changes

2021-03-30 08:07 UTC, ferferga approved these changes

2021-03-30 08:08 UTC, MrTimscampi commented
@jellyfin rebase

2021-03-30 08:17 UTC, merged