ci(rebase): react on comment when rebase starts
jellyfin/jellyfin-vue pull request #952
Opened 2021-04-03 16:38 UTC by MrTimscampi

This should (in theory) give some feedback that the comment for rebasing has been seen by the action, but adding :+1: as a reaction to it.

2021-04-03 16:38 UTC, MrTimscampi commented
@jellyfin-bot rebase

2021-04-03 17:02 UTC, ThibaultNocchi approved these changes

2021-04-03 20:16 UTC, MrTimscampi commented
@jellyfin-bot rebase

2021-04-03 20:39 UTC, ferferga approved these changes

2021-04-03 20:55 UTC, ferferga requested changes

2021-04-03 20:55 UTC, ferferga commented on .github/workflows/rebase.yml
> +        uses: peter-evans/create-or-update-comment@v1
```suggestion
        uses: peter-evans/create-or-update-comment@v1.4.4
```

Per marketplace **Use latest button**: https://github.com/marketplace/actions/create-or-update-comment

2021-04-04 08:18 UTC, ferferga approved these changes

2021-04-04 08:27 UTC, merged