fix(ux): always update loading status and update server data on login
jellyfin/jellyfin-vue pull request #953
Opened 2021-04-04 05:37 UTC by dkanada

2021-04-04 16:03 UTC, ThibaultNocchi commented
Idk how it was before, but the branding appearing after the page load is kinda janky

2021-04-04 17:16 UTC, MrTimscampi commented
> Idk how it was before, but the branding appearing after the page load is kinda janky

We can remove the keep-alive prop in `fullpage.vue` (since it's only used for the login flow anyway) and revert the fetch bits to fix this.

2021-04-06 08:34 UTC, MrTimscampi requested changes
Looks good, but there's a nicer UX solution for the fetching issue :yum:

2021-04-06 08:34 UTC, MrTimscampi commented on client/pages/server/login.vue
> -      const brandingData = (await $api.branding.getBrandingOptions()).data;
As @ThibaultNocchi mentioned, moving the branding to `fetch()` makes it a bit jarring (Same for public users).

As a proper fix for them not being refreshed, while keeping the nicer experience, we can add an exclude list to the `keep-alive` here: https://github.com/jellyfin/jellyfin-vue/blob/master/client/layouts/fullpage.vue#L4

Just exclude the server pages (We might use fullpage for other things in the future) and that should fix these not being re-fetched when in `asyncData`.

2021-04-06 08:35 UTC, MrTimscampi commented on client/pages/server/login.vue
> -      const brandingData = (await $api.branding.getBrandingOptions()).data;
More info on the available keep-alive props: https://v3.vuejs.org/api/built-in-components.html#keep-alive

2021-04-08 11:30 UTC, MrTimscampi approved these changes

2021-04-08 11:31 UTC, merged